# action.yml
name: 'Neo4j Deploy Plugin'
description: 'Deploy a Neo4j plugin to a remote Neo4j server'
inputs:
  local-plugin-file:  
    description: 'Plugin JAR file to be deployed to Neo4j'
    required: true
  
  remote-host:  
    description: 'Host address of remote Neo4j server'
    required: true

  remote-port:  
    description: 'Port of remote Neo4j server'
    required: false
    default: '22'

  remote-user:  
    description: 'Username on remote Neo4j server'
    required: true

  remote-password:  
    description: 'Password on remote Neo4j server'
    required: false

  remote-ssh-key-content:  
    description: 'SSH private key content'
    required: false

  remote-ssh-key-file:  
    description: 'SSH private key file'
    required: false

  remote-ssh-key-passphrase:
    description: 'Passphrase to decrypt SSH private key'
    required: false

  remote-plugin-dir:
    description: 'Remote plugin directory on Neo4j'
    required: false
    default: '/var/lib/neo4j/plugins'

runs:
  using: "composite"
  steps:
    - name: Check if remote SSH key or password was provided
      if: ${{ github.event.inputs.remote-password ==  '' && github.event.inputs.remote-ssh-key-content == '' && github.event.inputs.remote-ssh-key-file == '' }}
      shell: bash
      run: | 
        echo "::error ::No remote SSH key or password was provided"
        exit 1

    - name: Check if plugin is a JAR file
      if: ${{ !endsWith(github.event.inputs.local-plugin-file, '.jar') }}
      shell: bash
      run: | 
        echo "::error ::Local plugin file is not a JAR file"
        exit 1   

    - name: Upload plugin to remote Neo4j server
      if: ${{ success() }}
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.remote-host }}
        port: ${{ inputs.remote-port }}
        username: ${{ inputs.remote-user }}
        password: ${{ inputs.remote-password }}
        key: ${{ inputs.remote-ssh-key-content }}
        key_path: ${{ inputs.remote-ssh-key-file }}
        passphrase: ${{ inputs.remote-ssh-key-passphrase }}
        source: ${{ inputs.local-plugin-file }}
        target: "."

    - name: Move plugin to target directory and update permissions
      if: ${{ success() }}
      uses: appleboy/ssh-action@master
      with:
        host: ${{ inputs.remote-host }}
        username: ${{ inputs.remote-user }}
        password: ${{ inputs.remote-password }}
        port: ${{ inputs.remote-port }}
        key: ${{ inputs.remote-ssh-key-content }}
        key_path: ${{ inputs.remote-ssh-key-file }}
        passphrase: ${{ inputs.remote-ssh-key-passphrase }}
        script_stop: true
        script: |
          SOURCE_FILE=$(basename ${{ inputs.local-plugin-file }})
          TARGET_PATH=${{ inputs.remote-plugin-dir }}/$SOURCE_FILE
          echo "Moving $SOURCE_FILE to $TARGET_PATH"
          sudo mv ${{ env.SOURCE_FILE }} ${{ env.TARGET_PATH }}
          echo "Changing owner and group to neo4j:neo4j"
          sudo chown -R neo4j:neo4j ${{ env.TARGET_PATH }}
          echo "Changing mode to executable"
          sudo chmod +x ${{ env.TARGET_PATH }}